In [1]:
from numpy import array
import numpy as np

## 1. Matrix Multiplication: Element-wise

In [ ]:
A = array([
 [1, 2, 3],
 [4, 5, 6]
])
print("A's shape: {}".format(A.shape,))
print(A)

In [ ]:
B =  array([
 [2, 4, 6],
 [8, 10, 12]
])
print("B's shape: {}".format(B.shape,))
print(B)

In [ ]:
C = A * B
print("C's shape: {}".format(C.shape,))
print(C)

## 2. Matrix-Vector Multiplication: Broadcasting

In [ ]:
A = array([
    [1, 2], 
    [3, 4], 
    [5, 6]
])
print("A's shape: {}".format(A.shape,))
print(A)

In [ ]:
B = array([2, 3])
print("B's shape: {}".format(B.shape,))
print(B)

In [ ]:
C = A + B
print("C's shape: {}".format(C.shape,))
print(C)

## 3. Dot Product

In [ ]:
A = array([
    [1, 2], 
    [3, 4], 
    [5, 6]
])
print("A's shape: {}\n".format(A.shape,))
print(A)


In [ ]:
B = array([
    [1, 2], 
    [3, 4]
])
print("B's shape: {}\n".format(B.shape,))
print(B)

In [ ]:
C = A.dot(B)
print("C's shape: {}\n".format(C.shape,))
print(C)

## 4. Python Loops vs. Numpy Matrix Operations

In [1]:
from numpy import random
import timeit

X = random.randint(10, size=(10, 10))
Y = random.randint(10, size=(10, 10))

print("Matrix X:\n {}".format(X))
print("Matrix Y:\n {}".format(Y))

Matrix X:
 [[0 8 6 2 9 4 5 2 6 6]
 [6 2 1 3 7 9 1 1 6 7]
 [3 1 8 3 9 0 1 8 8 8]
 [6 3 4 3 4 0 2 1 1 1]
 [0 4 7 3 3 4 2 3 2 6]
 [7 5 4 3 1 8 2 3 0 7]
 [7 9 5 8 6 0 5 8 7 8]
 [7 4 1 4 7 8 0 6 6 8]
 [1 8 3 4 7 8 2 2 4 9]
 [5 9 0 9 7 1 8 6 5 2]]
Matrix Y:
 [[4 5 5 3 4 1 5 6 9 6]
 [1 0 4 3 9 4 7 9 7 8]
 [9 9 9 0 2 7 6 0 7 0]
 [9 2 6 0 4 8 9 0 0 6]
 [9 7 1 3 5 6 3 7 5 4]
 [5 5 0 3 1 3 7 9 8 0]
 [1 3 4 9 7 1 0 3 6 3]
 [0 7 3 1 4 6 4 8 1 2]
 [5 5 2 3 0 3 6 3 3 4]
 [5 7 1 4 9 4 6 6 4 9]]


In [3]:
def add_python(X, Y):
    return [[X[i][j] + Y[i][j]  for j in range(len(X[0]))] for i in range(len(X))]

def add_numpy(X, Y):
    return np.add(X, Y)

In [6]:
timeit.timeit('add_numpy(X, Y)', globals=globals())

0.611908845000471

In [7]:
timeit.timeit('add_python(X, Y)', globals=globals())

64.48518569099997

## 5. Normalization

In [ ]:
from numpy import array
import numpy as np

a = array([0.1, 5, 12, 100])
print("Mean: {}".format(a.mean(axis=0)))
a -= a.mean(axis=0)
print("After deduct mean: {}".format(a))


In [ ]:
print("Standard Deviation: {}".format(a.std(axis=0)))
a /= a.std(axis=0)
print("After normalization: {}".format(a))

In [ ]:
print("Standard Deviation of the normalized array: {}".format(a.std(axis=0)))

## 6. Chain Rules

In [8]:
# sympy does symbolic differentiation
import sympy as sp
from sympy import *

x = sp.symbols('x')
y = sp.symbols('y')

f = 2*x
g = pow(f, 2)# g = f(x)**2

# Calculate the derivative to x
g_x_d = g.diff()

g_x_d

8*x

## 7. Gradient for a two variables function

In [9]:
m=sp.Matrix([[x],[y]])
f = x**2-x*y

f_x_y_d = [sp.diff(f, i) for i in m]
f_x_y_d

[2*x - y, -x]

## 8. Softmax Function

In [ ]:
def softmax(y):
    """Compute softmax values for each sets of scores in y."""
    return np.exp(y) / np.sum(np.exp(y), axis=0)

In [ ]:
# Let's say we want to classify: dog, pig, chickren, duck
scores = [1,2,3,4]
print(softmax(scores))

## 9. Activation Functions

### 1. Sigmod 

In [ ]:
#sigmoid activation function
def sigmoid(x, derivative=False):
    if(derivative==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

![Sigmoid](images/sigmoid.gif)

In [ ]:
sigmoid(-5)

## 10. 2D Convolution

In [3]:
import numpy as np
from scipy import signal

In [4]:
input_matrix = np.array(
             [[1, 1, 1, 0, 0],
              [0, 1, 1, 1, 0],
              [0, 0, 1, 1, 1],
              [0, 0, 1, 1, 0],
              [0, 1, 1, 0, 0]],
             dtype='float')

kernal = np.array(
               [[1, 0, 1],
                [0, 1, 0],
                [1, 0, 1],],
               dtype='float')

### Output Size: (5 - 3 + 2*0)/1 + 1 = 3

In [5]:
signal.convolve2d(input_matrix, kernal, mode='valid')

array([[4., 3., 4.],
       [2., 4., 3.],
       [2., 3., 4.]])

In [6]:
signal.convolve2d(input_matrix, kernal, mode='same')

array([[2., 2., 3., 1., 1.],
       [1., 4., 3., 4., 1.],
       [1., 2., 4., 3., 3.],
       [1., 2., 3., 4., 1.],
       [0., 2., 2., 1., 1.]])

## 11. He et al. Weight Initialization.

## Normal Distribution

In [ ]:
F_in = 64
F_out = 32

sd = np.sqrt(2/float(F_in))
print("Standard Deviation: {}".format(sd))

W = np.random.normal(0.0, sd, size=(F_in, F_out))
print("Shape: {}".format(W.shape))
W

## Uniform Distribution

In [ ]:
limit = np.sqrt(6 / float(F_in))
np.random.uniform(low=-limit, high=limit, size=(F_in, F_out))